services:
  - type: web
    name: ems-ai-triage
    env: python
    buildCommand: pip install -r requirements_fastapi.txt
    startCommand: uvicorn fastapi_app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
